// <auto-generated />
using System;
using CadastroWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CadastroWebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CadastroWebApi.Models.Cliente", b =>
                {
                    b.Property<long>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Bairro")
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Estado")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .HasColumnType("text");

                    b.Property<string>("Sexo")
                        .HasColumnType("text");

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            ClienteId = 1L,
                            Bairro = "Muggles",
                            Cep = "95055-268",
                            Cidade = "Maringá",
                            Complemento = "",
                            DataNascimento = new DateTime(1995, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PR",
                            Nome = "Matheus Gomes Roberto dos Santos",
                            Numero = "4",
                            Rua = "Rua Alfeiros",
                            Sexo = "Maculino"
                        },
                        new
                        {
                            ClienteId = 2L,
                            Bairro = "Muggles",
                            Cep = "95055-268",
                            Cidade = "Maringá",
                            Complemento = "",
                            DataNascimento = new DateTime(1999, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PR",
                            Nome = "Lucas Souza de Gois",
                            Numero = "4",
                            Rua = "Rua Alfeiros",
                            Sexo = "Maculino"
                        },
                        new
                        {
                            ClienteId = 3L,
                            Bairro = "Gopauva",
                            Cep = "823489-025",
                            Cidade = "São Paulo",
                            Complemento = "",
                            DataNascimento = new DateTime(1941, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "SP",
                            Nome = "Bethy da Silva",
                            Numero = "257",
                            Rua = "Alameda Yaya",
                            Sexo = "Feminino"
                        },
                        new
                        {
                            ClienteId = 4L,
                            Bairro = "Fim do Universo",
                            Cep = "78964-568",
                            Cidade = "Maringá",
                            Complemento = "Apt. 1101",
                            DataNascimento = new DateTime(1996, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Estado = "PR",
                            Nome = "Lívia Peron Bernardo",
                            Numero = "42",
                            Rua = "Rua da Toalha",
                            Sexo = "Feminino"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
